/******************************************************************************
 * Copyright 2025 The Openbot Authors (duyongquan)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************/

#pragma once

#include "autoview/common/properties/property.hpp"

namespace autoview {
namespace common {
namespace properties {

/// Property specialized to provide max/min enforcement for integers.
class IntProperty : public Property
{
  Q_OBJECT

public:
  /// Constructor.
  /**
   * \param name The name of this property.
   *   Appears in the left column of a PropertyTreeWidget.
   * \param default_value The initial value to store in the property.
   *   Appears in the right column of a PropertyTreeWidget.
   * \param description Text describing the property.
   *   Is shown in the "help" area of a PropertyTreeWithHelp widget.
   * \param parent The parent Property, or NULL if there is no parent at this
   *   time.
   * \param changed_slot This should be a Qt slot specification,
   *   generated by Qt's @c SLOT() macro.
   *   It should be a slot on the receiver object, or if receiver is not
   *   specified, it should be a slot on the parent.
   * \param receiver If receiver is non-NULL, the changed() signal is
   *   connected to the changed_slot on the receiver object.
   */
  explicit IntProperty(
    const QString & name = QString(),
    int default_value = 0,
    const QString & description = QString(),
    Property * parent = 0,
    const char * changed_slot = 0,
    QObject * receiver = 0,
    int min_value = INT_MIN,
    int max_value = INT_MAX);

  /// Set the new value for this property.
  /**
   * Returns true if the new value is different from the old value, else false.
   *
   * If the new value is different from the old value, this emits
   * aboutToChange() before changing the value and changed() after.
   *
   * Overridden from Property::setValue() to enforce minimum and maximum.
   */
  bool setValue(const QVariant & new_value) override;

  /// Return the internal property value as an integer.
  /**
   * If a non-integer value was stored in this property, this will return 0.
   */
  virtual int getInt() const;

  /// Set the minimum value to be enforced.
  void setMin(int min);

  /// Set the minimum value enforced.
  int getMin();

  /// Set the maximum value to be enforced.
  void setMax(int max);

  /// Get the maximum value to be enforced.
  int getMax();

  /// Called when the editor is created.
  /**
   * Overridden to create a QSpinBox with the min and max set and with a
   * signal/slot connection to setInt(), so the Property value updates every
   * time the value changes, not just when "return" is pressed.
   */
  QWidget * createEditor(QWidget * parent, const QStyleOptionViewItem & option) override;

public Q_SLOTS:
  /// Set the value of this property to the given integer.
  /**
   * This just calls setValue(), which is where the min/max are enforced.
   */
  void setInt(int new_value);

private:
  int min_;
  int max_;
};

}  // namespace properties
}  // namespace common
}  // namespace autoview